language: csharp
solution: SampleWebAPI.sln
# mono: none
# dotnet: 1.0.1
# dist: trusty
install:
  - nuget restore SampleWebAPI.sln
  - nuget install NUnit.Runners -Version 3.4.1 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release SampleWebAPI.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.4.1/tools/nunit3-console.exe ./SampleWebAPITests/bin/Release/SampleWebAPITests.dll
deploy:
  provider: azure_web_apps
  verbose: true
before_deploy: "rm .gitignore; git add .; git commit -a -m 'adding build files'"
