language: csharp
solution: SampleWebAPI.sln
# mono: none
# dotnet: 1.0.1
# dist: trusty
install:
  - nuget restore SampleWebAPI.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release SampleWebAPI.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./SampleWebAPITests/bin/Release/SampleWebAPITests.dll
